name: CI/CD EP3 User Service

on:
  push:
    branches:
      - deploy

jobs:
  build-and-deploy:
    name: Build, Push y Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codigo
        uses: actions/checkout@v4

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login en Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build y Push imagen a ECR
        run: |
          docker build -t ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:latest .
          docker push ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:latest

      - name: Actualizar servicio ECS
        run: |
          aws ecs update-service \
            --cluster cluster-innovatech-ep3 \
            --service ${{ secrets.ECS_SERVICE }} \
            --force-new-deployment \
            --region ${{ secrets.AWS_REGION }}

      - name: Esperar despliegue estable
        run: |
          aws ecs wait services-stable \
            --cluster cluster-innovatech-ep3 \
            --services ${{ secrets.ECS_SERVICE }} \
            --region ${{ secrets.AWS_REGION }}

      - name: Despliegue completado
        run: echo "Servicio ${{ secrets.ECS_SERVICE }} desplegado correctamente"